// db/schema.js
const {
  pgTable,
  serial,
  text,
  boolean,
  timestamp,
  integer,
} = require("drizzle-orm/pg-core");

// ✅ 1. Should be `module.exports`, not `module.export`
// ✅ 2. Return all tables as named exports at the end

const users = pgTable("users", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  password: text("password_hash").notNull(), // keep naming consistent with code
  lastSeen: timestamp("last_seen").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

const devices = pgTable("devices", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  deviceId: text("device_id").notNull().unique(), // UUID generated by client
  deviceName: text("device_name"),
  publicKey: text("public_key").notNull(),
  refreshToken: text("refresh_token"), // ✅ optional addition
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

const messages = pgTable("messages", {
  id: serial("id").primaryKey(),
  senderId: integer("sender_id").notNull(),
  receiverId: integer("receiver_id").notNull(),
  ciphertext: text("ciphertext").notNull(),
  deviceId: text("device_id").notNull(),
  msgType: text("msg_type").default("text"),
  delivered: boolean("delivered").default(false),
  createdAt: timestamp("created_at").defaultNow(),
});

// ✅ Export all tables
module.exports = { users, devices, messages };
